// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AKUNOU_MapScrollDisable","status":true,"description":"プレイヤーキャラの移動に同期した画面スクロールを、一時的に無効にするプラグインコマンドを追加します。","parameters":{}}
];
